spring.application.name=com



# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/canteen
spring.datasource.username=root
spring.datasource.password=Mahi2018

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


jwt.secret=CampusCanteenProjectSecretKeyForJwtAuthentication2026VerySecureKey
jwt.expiration=86400000